apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kavinduchamiran/cloudl-server:v1
          ports:
            - containerPort: 8000
              name: nodejs-port
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
  selector:
    matchLabels:
      app: backend
