apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::445567118310:user/gitops      
      username: gitops      
      groups:        
        - system:masters
