apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_URI:
    bW9uZ29kYitzcnY6Ly9wcmluY2VndXB0YTQ0NDU1NTpOMFh5RTJXQjRxWEtjeHRpQGNsdXN0ZXIw
    Lmw4bWd4ZnUubW9uZ29kYi5uZXQ=
