apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 445567118310.dkr.ecr.us-east-2.amazonaws.com/blogapp:latest
          ports:
            - containerPort: 5173
              name: http-port
  selector:
    matchLabels:
      app: frontend
