name: Build and Deploy to AWS EKS
on: workflow_dispatch

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_BACKEND }}
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_FRONTEND }}

      # Build and push backend Docker image
      - name: Build backend Docker image
        run: |
          docker build -t backend:latest ./backend
          docker tag backend:latest ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest

      - name: Push backend Docker image
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest

      # Build and push frontend Docker image
      - name: Build frontend Docker image
        run: |
          docker build -t frontend:latest ./frontend
          docker tag frontend:latest ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest

      - name: Push frontend Docker image
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest

  deploy:
    name: Deploy to Kubernetes on AWS EKS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f ./kubernetes/blog-app
